chatGPT/chatGPT/urls.py
from django.urls import path, include
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('', include('pictures.urls', namespace='pictures')),
    path('admin/', admin.site.urls),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

chatGPT/pictures/urls.py
from django.urls import path
from .views import picture_view, picture_view_list, picture_detail

app_name = 'pictures'

urlpatterns = [
    path('', view=picture_view, name='index'),
    path('list/', view=picture_view_list, name='list'),
    path('detail/<int:id>/', view=picture_detail, name='detail'),
]

chatGPT/pictures/models.py
from django.db import models
from sorl.thumbnail import ImageField


class Pictures(models.Model):
    name = models.CharField(
        max_length=200,
        blank=False,
        null=False,
    )
    picture = ImageField(
        'Picture',
        upload_to='pictures/',
        blank=True,
    )
    picture_url = models.URLField(
        max_length=1000,
        blank=False,
        null=False,
    )
    pub_date = models.DateTimeField(
        auto_now_add=True,
    )

    class Meta:
        ordering = ('-pub_date',)

    def __str__(self):
        return self.name

chatGPT/pictures/forms.py
from django import forms
from .models import Pictures
from django.core.exceptions import ValidationError


class PictureForm(forms.ModelForm):

    class Meta:
        fields = ('name',)
        model = Pictures

    def validate_name(value):
        if not value:
            raise ValidationError('String field cannot be empty.')

chatGPT/pictures/views.py
from pictures.forms import PictureForm
from django.shortcuts import render, redirect, get_object_or_404
from pictures.models import Pictures
from pictures.gpt import GPT_function, creating_picture


def picture_view(request):
    template = 'pictures/index.html'
    form = PictureForm
    context = {
        'form': form
    }
    if request.method != 'POST':
        form = PictureForm()
        return render(request, template, context)
    form = PictureForm(request.POST)
    if form.is_valid():
        name = form.data['name']
        form.save()

        my_picture = Pictures.objects.filter(name__exact=name)[0]
        gpt_return = GPT_function(name)
        print(gpt_return)
        if gpt_return == 'http://unavailable':
            my_picture.delete()
            return redirect('pictures:index')
        my_picture.picture_url = gpt_return
        creating_picture(my_picture)
        my_picture.save()
        return redirect('pictures:list')
    return render(request, template, context)


def picture_view_list(request):
    objects = Pictures.objects.all()
    context = {
        'objects': objects
    }
    template = 'pictures/list.html'
    return render(request, template, context)


def picture_detail(request, id):
    obj = get_object_or_404(Pictures, id=id)
    context = {
        'object': obj
    }
    template = 'pictures/detail.html'
    return render(request, template, context)

chatGPT/templates/pictures/detail.html
<!DOCTYPE html>
<html>
<head>
	<title>Picture</title>
    <style>
        body {
          background-color: black;
          font-family: sans-serif;
        }
        
        h1 {
          text-align: center;
        }
  
        h3 {
          text-align: center;
        }
        
        
        
        .center {
          display: flex;
          justify-content: center;
          align-items: center;
          height: 100vh;
        }
      </style>
</head>
<body>
    {% load thumbnail %}
    <div class="center">
      <div>
        <h1> {{object.name }} </h1>
        {% thumbnail object.picture "1024x1024" crop="center" upscale=True as im %}
          <img src="{{ im.url }}">
        {% endthumbnail %}
      </div>
    </div>
  </body>
</html>

chatGPT/templates/pictures/index.html
<!DOCTYPE html>
<html>
  <head>
    <title>My Page</title>
    <style>
      body {
        background-color: white;
        font-family: sans-serif;
      }
      
      h1 {
        text-align: center;
      }
      
      form {
        max-width: 500px;
        margin: 0 auto;
        padding: 20px;
        border: 1px solid #ccc;
        background-color: #f7f7f7;
      }
      
      label {
        display: block;
        margin-bottom: 10px;
        font-weight: bold;
      }
      
      input[type="text"], input[type="file"] {
        display: block;
        margin-bottom: 20px;
        padding: 10px;
        border: 1px solid #ccc;
        width: 100%;
        box-sizing: border-box;
        font-size: 16px;
      }
      
      input[type="submit"] {
        background-color: #4CAF50;
        color: white;
        padding: 10px 20px;
        border: none;
        border-radius: 5px;
        font-size: 16px;
        cursor: pointer;
      }
      
      input[type="submit"]:hover {
        background-color: #45a049;
      }
    </style>
  </head>
  
  <body>
    <h1>Welcome to AI generated</h1>
    <form action="#" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <label for="name">Enter what you wanna draw:</label>
        <input type="text" id="name" name="name">
      
      <input type="submit" value="Submit">
    </form>
    <h1><a href="{% url 'pictures:list' %}"> Galary </a></h1>
  </body>
</html>

chatGPT/templates/pictures/list.html
<!DOCTYPE html>
<html>
  <head>
    <title>My Object List</title>
    <style>
      body {
        background-color: white;
        font-family: sans-serif;
      }
      
      h1 {
        text-align: center;
      }

      h3 {
        text-align: center;
      }

      ul {
        list-style: none;
        margin: 0;
        padding: 0;
        display: flex;
        flex-wrap: wrap;
        justify-content: space-between;
      }
      
      li {
        width: calc(33.33% - 10px);
        margin-bottom: 20px;
        padding: 20px;
        border: 1px solid #ccc;
        background-color: #f7f7f7;
        box-sizing: border-box;
        text-align: center;
      }
      
      li img {
        max-width: 100%;
        height: auto;
        margin-bottom: 10px;
      }
      
      li h2 {
        margin-top: 0;
      }
    </style>
  </head>
  {% load thumbnail %}
  <body>
    <h1>Chat-GPT generated</h1>
    <h3><a href="{% url 'pictures:index'%}">Back to Generation page</a></h3>
    <ul>
        {% for object in objects%}
            <li>
                {% thumbnail object.picture "1024x1024" crop="center" upscale=True as im %}
                  <img src="{{ im.url }}">
                {% endthumbnail %}
                <h2><a href="{% url 'pictures:detail' object.id %}">{{ object.name }}</a></h2>
            </li>
        {% endfor%}
    </ul>
  </body>
</html>